query GetLatestVersion( $publishId: ID!) {
    publishVersions(
      first: 1,
      filter: {
          where: {
              publish: {
                  id: {equalTo: $publishId}
              }
          },
          withDeleted: true
      },
      ordering: {
        sort: NAME,
        direction: DESC
      }
    ) {
        edges {
            node {
                id
                name
            }
        }
        pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
        }
    }
}