
# current user
CURRENT_USER_ID = 'AGIO_CURRENT_USER_ID'
# current company
COMPANY_ID = 'AGIO_COMPANY_ID'
# workspace
WORKSPACE_ID = 'AGIO_WORKSPACE_ID'
REVISION_ID = 'AGIO_WORKSPACE_REVISION_ID'
WORKSPACE_SUFFIX = 'AGIO_WORKSPACE_SUFFIX'
INSTALL_PATH = 'AGIO_INSTALL_PATH'
DEFAULT_WORKSPACE_PY_EXECUTABLE = 'AGIO_DEFAULT_WORKSPACE_PY_EXECUTABLE'    # not used now
FORCE_DEFAULT_WORKSPACE = 'AGIO_FORCE_DEFAULT_WORKSPACE' # not used now
# settings
SETTINGS_REVISION_ID = 'AGIO_SETTINGS_REVISION_ID'
SETTINGS_DIR = 'AGIO_SETTINGS_DIR'
# packages
GIT_REPOSITORY_TOKEN = 'AGIO_GIT_REPOSITORY_TOKEN'
# entities
PROJECT_ID = 'AGIO_PROJECT_ID'
TASK_ID = 'AGIO_TASK_ID'
ENTITY_ID = 'AGIO_ENTITY_ID'
# apps
APP_NAME = 'AGIO_APP_NAME'
APP_VERSION = 'AGIO_APP_VERSION'
APP_GROUPS = 'AGIO_APP_GROUPS'
# logging
LOG_DIR = 'AGIO_LOG_DIR'
LOG_LEVEL = 'AGIO_LOG_LEVEL'
LOG_FILE_PREFIX ='AGIO_LOG_FILE_PREFIX'
LOG_FILE_SIZE ='AGIO_LOG_FILE_SIZE'
FILE_LOG_LEVEL = 'AGIO_FILE_LOG_LEVEL'
LOGGING_MESSAGE_FORMAT = 'AGIO_LOGGING_MESSAGE_FORMAT'
LOGGING_MESSAGE_FORMAT_CONSOLE = 'AGIO_LOGGING_MESSAGE_FORMAT_CONSOLE'
LOGGING_DATETIME_FORMAT = 'AGIO_LOGGING_DATETIME_FORMAT'
DISABLED_LOGGERS = 'AGIO_DISABLED_LOGGERS'
# other
DEBUG = 'AGIO_DEBUG'
DEBUG_QUERY = 'AGIO_DEBUG_QUERY'
ALLOW_COMMAND_OUTPUT_TO_CUSTOM_PIPE = 'AGIO_ALLOW_COMMAND_OUTPUT_TO_CUSTOM_PIPE'
FORCED_GIT_SERVICE = 'AGIO_FORCED_GIT_SERVICE'
FILE_NO_ENV = 'AGIO_FILE_NO_ENV'